apiVersion: v1
kind: Service
metadata:
  name: vitepress-knowledge-server
  labels:
    app: vitepress-knowledge-server
spec:
  selector:
    app: vitepress-knowledge-server
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  type: ClusterIP
