name: Validate
on:
  pull_request:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/setup
      - run: bun run build
      - run: bun check

  tests:
    name: Tests
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/setup
      - run: bun test

  actions-build:
    name: Actions Built
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/setup
      - run: bun run build
      - name: Check for git changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo -e "Error: Detected changes in actions/dist. These files should be committed.\n\nRun \`bun run build\` to update the actions and commit the change."
            git status
            git diff
            exit 1
          fi
